column(
    children:[
        Expanded(
            flex:4,
            child:container(
                color:Color.blue,
            ),
        ),
        container(
            height:10,
            color:Color.green,
        ),
        Expanded(
            flex:1
            child:container(
                color:colors.brown,
            ),
        )
    ],
)